import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata = {
	title: "ANIMEWEB",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${poppins.className} bg-color-dark `}
				suppressHydrationWarning={true}
			>
				<Navbar />
				{children}
				<Footer/>
			</body>
		</html>
	);
}

